[project]
name = "2"
version = "0.1.0"
description = ""
authors = [
    {name = "ssshevcova",email = "112807880+ssshevcova@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
